cache:
  key: "ruby25"
  paths:
  - vendor

variables:
  RSPEC_RETRY_RETRY_COUNT: "3"

before_script:
  - source ./scripts/prepare_build.sh
  - ruby -v
  - which ruby
  - retry bundle install --path vendor/bundle --without production --jobs $(nproc) "${FLAGS[@]}"
  - bin/rails db:environment:set RAILS_ENV=test

stages:
  - test
  - security
  - staging
  - production

rspec:
  stage: test
  script:
    - RAILS_ENV=test bundle exec rake db:drop db:create db:schema:load db:migrate db:seed
    - RAILS_ENV=test SIMPLECOV=true xvfb-run -a bundle exec rspec
  tags:
    - ruby2.5

rubocop:
  stage: test
  script:
    - bundle exec rubocop
  tags:
    - ruby2.5

brakeman:
  stage: security
  script:
    - bundle exec brakeman
  tags:
    - ruby2.5

bundler:audit:
  stage: security
  only:
    - master
    - staging
  script:
    - "bundle exec bundle-audit update"
    - "bundle exec bundle-audit check --ignore CVE-2017-8418"
  tags:
    - ruby2.5

deploy_staging:
  stage: staging
  environment:
    name: staging
    url: $WAVES_STAGING_URL
  only:
    - staging
  script:
    - bundle exec cap staging deploy
  tags:
    - ruby2.5

deploy_production:
 stage: production
 environment:
   name: production
   url: $WAVES_PRODUCTION_URL
 only:
   - production
 when: manual
 script:
   - bundle exec cap production deploy
 tags:
   - ruby2.5
